name: Kine build

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      kine_version:
        type: string
        description: Kine version tag for the image
        default: 0.13.5
        required: true

jobs:
  buildx:
    name: Build kine image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Fetch tags
        run: git fetch --tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine version
        id: determine_version
        run: echo "VERSION=${{ github.event.inputs.kine_version || github.ref_name }}" | sed 's/v//' >> $GITHUB_ENV
      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.release
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          provenance: true
          tags: ghcr.io/loft-sh/kine:v${{ env.VERSION }}
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ghcr.io/loft-sh/kine
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
