name: release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
      TAG: ${{ github.ref_name }}
    permissions:
      contents: write # Needed to update release with binary assets
      packages: write # Needed for GHCR image push
      id-token: write # needed for the Vault authentication
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binaries
        run: make multi-arch-build

      - name: Compute checksum for each binary
        run: |
          arch=("amd64" "arm64" "arm" "riscv64")
          cd dist/artifacts
          for a in "${arch[@]}"; do
            sha256sum kine-"${a}" > sha256sum-"${a}".txt
          done
          
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2.3.3 # https://github.com/softprops/action-gh-release/issues/587
        with:
          files: |
            dist/artifacts/kine-*
            dist/artifacts/*.txt
      
      - name: Login to GitHub Container Registry (loft-sh)
        if: github.repository_owner == 'loft-sh'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (loft-sh)
        if: github.repository_owner == 'loft-sh'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: .
          target: multi-arch-package
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kine:latest
            ghcr.io/${{ github.repository_owner }}/kine:${{ github.ref_name }}
